name: Bug report
description: File a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "What broke, in one or two sentences?"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1) …\n2) …\n3) …"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Logs
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "OS, versions, runtime"
  - type: textarea
    id: extra
    attributes:
      label: Additional context
