name: Bug report
description: Track a defect we need to fix
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      placeholder: "Quick note of the symptom and where you saw it."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      placeholder: "Why it matters, severity, who is blocked."
  - type: textarea
    id: steps
    attributes:
      label: Reproduction
      description: Share the minimal steps or command to trigger it.
      placeholder: "1) ...\n2) ...\n3) ..."
  - type: textarea
    id: notes
    attributes:
      label: Notes / Next moves
      placeholder: "Suspected cause, quick fix idea, follow-up tasks."
  - type: checkboxes
    id: readiness
    attributes:
      label: Ready to work?
      options:
        - label: Reproduced locally or in logs
        - label: Added any links/screenshots that matter
