name: Org Settings Report

on:
  schedule:
    - cron: '15 5 * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export org settings
        # ORG_REPORT_TOKEN must be scoped for read:org and admin:org so gh api calls succeed.
        env:
          GH_TOKEN: ${{ secrets.ORG_REPORT_TOKEN }}
        run: python3 scripts/export_org_settings.py
      - name: Commit report if changed
        shell: bash
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          set -euo pipefail

          branch="${GITHUB_REF_NAME:-main}"

          git config user.name "$GIT_COMMITTER_NAME"
          git config user.email "$GIT_COMMITTER_EMAIL"

          git fetch origin "$branch"
          git checkout "$branch"
          git pull --ff-only origin "$branch"

          git add docs/org-settings.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "docs: refresh org settings report"
          git push origin "HEAD:$branch"
